-- Populate Knowledge Base with News and Events data
-- This script inserts structured content from the news-events page

-- Insert social media posts as knowledge articles
INSERT INTO reddog.KnowledgeArticles (title, content, category, source, sourceUrl, publishedDate, tags, metadata) VALUES
('Control Centre Now Live', 
'Exciting progress on the Agentic Ag platform — our Control Centre is now live, giving farmers a single dashboard view across energy, IoT sensors, livestock, and AI agent activity in real time. Control systems with simple text messages — yes/no responses from anywhere. Australian farms deserve tools built for Australian conditions. That''s exactly what we''re building.',
'News',
'LinkedIn',
'https://www.linkedin.com/company/108727120/admin/feed/following/',
'2026-05-15',
'AgTech,PrecisionAgriculture,SmartFarming,IoT,AustralianAg',
'{"platform": "LinkedIn", "likes": 84, "comments": 12}'),

('The Control Centre Dashboard',
'The Control Centre — your whole farm on one screen. Real-time sensors, energy, livestock, and AI agents all connected. Control everything with simple text messages — no app needed!',
'News',
'Instagram',
'https://www.instagram.com/agentic_ag/',
'2026-05-15',
'AgenticAg,SmartFarm,FarmTech,IoT,AustralianFarming,ControlCentre',
'{"platform": "Instagram", "likes": 216, "comments": 31, "image": "Control Centre.png"}'),

('Soil Testing Integration Complete',
'We''ve just completed soil testing on a property in Northern NSW — results mapped directly into the platform, fertiliser prescriptions generated automatically. Variable rate application recommendations, carbon baseline data, and biological health scores — all in one dashboard-integrated report. This is precision agriculture done properly.',
'News',
'LinkedIn',
'https://www.linkedin.com/company/108727120/admin/feed/following/',
'2026-05-10',
'SoilHealth,PrecisionAg,CarbonFarming,SoilTesting,AgTech',
'{"platform": "LinkedIn", "likes": 107, "comments": 19}'),

('LoRaWAN Sensor Network Deployed',
'LoRaWAN sensor network deployed — 14 nodes across 800ha. Every soil probe, water meter, and weather station now feeding live data into the platform.',
'Technology',
'Instagram',
'https://www.instagram.com/agentic_ag/',
'2026-05-08',
'LoRaWAN,IoT,SmartFarm,FarmSensors,PrecisionAgriculture,AgTech',
'{"platform": "Instagram", "likes": 183, "comments": 24, "image": "Farm Sytems IoT Infrastructure.png"}'),

('FarmG8 Marketplace Development',
'The FarmG8 Marketplace is shaping up to be something special — connecting producers directly with buyers, CoOps, and processors with integrated logistics and carbon credit trading. No middlemen. Transparent pricing. Live stock availability synced directly from your Farmyard dashboard. Watch this space.',
'Marketplace',
'LinkedIn',
'https://www.linkedin.com/company/108727120/admin/feed/following/',
'2026-05-05',
'FarmG8,AgriMarketplace,DirectToFarm,CarbonCredits,FoodSupplyChain',
'{"platform": "LinkedIn", "likes": 134, "comments": 28}'),

('Carbon Sequestration Tracking',
'Carbon sequestration mapped and tracked at the paddock level. ERF-aligned methodology, biodiversity scoring, and compliance reports — all generated automatically.',
'Sustainability',
'Instagram',
'https://www.instagram.com/agentic_ag/',
'2026-05-01',
'CarbonFarming,ERF,Biodiversity,RegenerativeAg,SustainableFarming',
'{"platform": "Instagram", "likes": 247, "comments": 42, "image": "Agentic Ag Carbon.png"}');

-- Insert events as knowledge articles
INSERT INTO reddog.KnowledgeArticles (title, content, category, source, sourceUrl, publishedDate, tags, metadata) VALUES
('GRDC Grains Research Updates 2026',
'Annual tour of grains research findings across all major cropping states. Critical updates on variety trials, agronomy, and pest management. Held in February across WA, SA, VIC, NSW, and QLD.',
'Events',
'GRDC',
'https://grdc.com.au',
'2026-02-01',
'Grains,Agronomy,Research',
'{"eventType": "Conference", "states": ["WA", "SA", "VIC", "NSW", "QLD"], "month": "February"}'),

('Sydney Royal Easter Show 2026',
'Australia''s largest annual event celebrating agriculture, innovation, and rural life. Features livestock competitions, machinery displays, and agtech showcases. Held April 2-19 at Sydney Showground.',
'Events',
'Sydney Royal Easter Show',
'https://www.eastershow.com.au',
'2026-04-02',
'Livestock,Machinery,Agtech',
'{"eventType": "Show", "location": "Sydney Showground, Sydney NSW", "dates": "April 2-19"}'),

('Tocal Field Days 2026',
'Hands-on field day featuring the latest in farm machinery, pasture management, livestock, and agricultural technology demonstrations. Held at Tocal College, Paterson NSW in April.',
'Events',
'Tocal Field Days',
'https://www.tocal.com',
'2026-04-15',
'Field Day,Livestock,NSW',
'{"eventType": "Field Day", "location": "Tocal College, Paterson NSW", "month": "April"}'),

('Primex Field Days 2026',
'Northern NSW''s premier agricultural field day. Features machinery, livestock, land management, and agtech. Located at Casino Showground, Casino NSW (Northern Rivers) - right in the heart of Clarence Valley service region.',
'Events',
'Primex',
'https://www.primex.com.au',
'2026-05-15',
'Field Day,Northern NSW,Machinery,Land Management',
'{"eventType": "Field Day", "location": "Casino Showground, Casino NSW", "month": "May", "featured": true}'),

('Digital Agriculture Forum 2026',
'Australia''s growing digital agriculture community — covering precision ag, IoT, AI, robotics, and data-driven farm decision-making. Online/National event in May.',
'Events',
'Digital Agriculture Forum',
'https://agenticag.co/contact.html',
'2026-05-20',
'Digital Ag,IoT,AI,Online',
'{"eventType": "Conference", "format": "Online/National", "month": "May"}'),

('Hort Connections 2026',
'Australia''s largest national horticulture conference and trade show. Covers fresh produce, supply chains, agtech, and sustainability for the horticulture industry. Held at Brisbane Convention & Exhibition Centre, QLD in June.',
'Events',
'Hort Connections',
'https://www.hortconnections.com.au',
'2026-06-15',
'Horticulture,Trade Show,QLD,Agtech',
'{"eventType": "Conference", "location": "Brisbane Convention & Exhibition Centre, QLD", "month": "June", "featured": true}'),

('Carbon Farming Conference & Expo 2026',
'Australia''s dedicated carbon farming conference covering ERF methodology, soil carbon, biodiversity credits, and carbon market opportunities for landholders. National event in June.',
'Events',
'Carbon Farming Conference',
'https://agenticag.co/contact.html',
'2026-06-20',
'Carbon,ERF,Sustainability',
'{"eventType": "Conference", "location": "National - TBC", "month": "June"}'),

('AgQuip Field Days 2026',
'Australia''s largest agricultural field day — 500+ exhibitors across 3 days. Features machinery, irrigation, livestock equipment, precision ag, and the latest in farm technology including live IoT and drone demonstrations. Held August 18-20 in Gunnedah, NSW.',
'Events',
'AgQuip',
'https://www.agquip.com.au',
'2026-08-18',
'Field Day,Machinery,IoT,Drones,NSW',
'{"eventType": "Field Day", "location": "Gunnedah, NSW", "dates": "August 18-20", "featured": true}'),

('Ekka - Royal Queensland Show 2026',
'Queensland''s premier agricultural show. Features livestock, produce, innovation showcases, and rural lifestyle. A major meeting point for the Queensland farming community. Held at Brisbane Showgrounds, QLD in August.',
'Events',
'Ekka',
'https://www.ekka.com.au',
'2026-08-10',
'Show,Livestock,QLD',
'{"eventType": "Show", "location": "Brisbane Showgrounds, QLD", "month": "August"}'),

('Royal Melbourne Show 2026',
'Victoria''s iconic annual agricultural show featuring livestock competitions, harvest produce, rural innovation, and a major agtech and machinery precinct. Held at Melbourne Showgrounds, VIC in September-October.',
'Events',
'Royal Melbourne Show',
'https://www.royalshow.com.au',
'2026-09-15',
'Show,Livestock,VIC,Agtech',
'{"eventType": "Show", "location": "Melbourne Showgrounds, VIC", "dates": "September-October", "featured": true}'),

('Elmore Field Days 2026',
'One of Victoria''s largest agricultural field days covering cropping, livestock, irrigation, and precision agriculture. Strong contingent of machinery and agtech exhibitors. Held in Elmore, VIC in October.',
'Events',
'Elmore Field Days',
'https://www.elmorefielddays.com.au',
'2026-10-10',
'Field Day,VIC,Cropping,Precision Ag',
'{"eventType": "Field Day", "location": "Elmore, VIC", "month": "October"}'),

('Australian Grains Conference 2026',
'Strategic outlook for the Australian grains industry — covering market conditions, technology adoption, export trends, and on-farm innovation. National event in November.',
'Events',
'Australian Grains Conference',
'https://agenticag.co/contact.html',
'2026-11-15',
'Grains,Conference,Markets',
'{"eventType": "Conference", "location": "National - TBC", "month": "November"}'),

('NFF National Farmers'' Congress 2026',
'Australia''s peak farming organisation annual congress — policy, advocacy, and strategic direction for Australian agriculture. Key networking event for the sector. Held in Canberra, ACT in November.',
'Events',
'National Farmers Federation',
'https://www.nff.org.au',
'2026-11-20',
'Policy,NFF,ACT,National',
'{"eventType": "Congress", "location": "Canberra, ACT", "month": "November"}');

-- Insert service information as knowledge articles
INSERT INTO reddog.KnowledgeArticles (title, content, category, source, sourceUrl, tags, metadata) VALUES
('Soil Testing Services',
'Professional farm soil testing across Clarence Valley, Brunswick, Nambucca catchments, and Northern Tablelands. Laboratory analysis provided by Southern Cross University Environmental Analysis Laboratory (EAL). Services include Agricultural Soil Testing, Acid Sulfate Soil Testing, General Soils & Solids Testing, Plant Testing, Water & Liquid Testing, and Compost & Landscape Soils testing. Pricing varies by service type.',
'Services',
'Agentic Ag',
'https://agenticag.co/soil-testing.html',
'SoilTesting,SCU EAL,Laboratory Analysis',
'{"provider": "Southern Cross University Environmental Analysis Laboratory (EAL)", "regions": ["Clarence Valley", "Brunswick", "Nambucca", "Northern Tablelands"]}'),

('Land Management Services',
'On-the-ground land management and smart hobby farm design across the North Coast NSW from Tweed Heads to Coffs Harbour. Services include Farm Landscape Design & Planning, Dam Construction & Repairs, Driveways & Farm Tracks ($1,000/day), Hardstands & Equipment Pads, Erosion Control & Revegetation, Drainage & Flood Recovery, and Land Clearing & Weed Management (Mulching: $250/hr).',
'Services',
'Agentic Ag',
'https://agenticag.co/land-management.html',
'LandManagement,Earthworks,Farm Design',
'{"regions": ["Tweed Heads", "Byron Bay", "Clarence Valley", "Nambucca", "Coffs Harbour"], "pricing": {"driveways": "$1,000/day", "mulching": "$250/hr"}}'),

('IoT Installation Services',
'Comprehensive IoT sensor network installation and integration for smart farms. LoRaWAN networks, soil probes, water meters, weather stations, and automated control systems. Dashboard-integrated monitoring and alerts.',
'Services',
'Agentic Ag',
'https://agenticag.co/iot-installation.html',
'IoT,Sensors,LoRaWAN,Smart Farm',
'{"technologies": ["LoRaWAN", "Soil Probes", "Water Meters", "Weather Stations"]}'),

('Drone Services',
'Drone flights and processing for agricultural applications. Aerial mapping, crop monitoring, NDVI analysis, livestock counting, and precision agriculture data collection.',
'Services',
'Agentic Ag',
'https://agenticag.co/drones.html',
'Drones,Aerial Mapping,Precision Ag,NDVI',
'{"services": ["Aerial Mapping", "Crop Monitoring", "NDVI Analysis", "Livestock Counting"]}'),

('Consultancy & Systems Integration',
'Expert consultancy for agricultural technology integration. Farm system design, technology planning, and implementation support for IoT, automation, and data-driven farming.',
'Services',
'Agentic Ag',
'https://agenticag.co/consultancy.html',
'Consultancy,Systems Integration,Farm Technology',
'{"focus": ["Farm System Design", "Technology Planning", "Implementation Support"]}'),

('Bioenergy Co-Op',
'Cooperative bioenergy solutions for agricultural operations. Shared infrastructure, renewable energy systems, and sustainable power generation for farm communities.',
'Services',
'Agentic Ag',
'https://agenticag.co/bioenergy-coop.html',
'Bioenergy,Renewable Energy,Cooperative',
'{"focus": ["Shared Infrastructure", "Renewable Energy", "Sustainable Power"]}'),

('Carbon, Biodiversity & Restoration',
'Carbon farming, biodiversity assessment, and ecological restoration services. ERF-aligned methodology, carbon sequestration tracking, biodiversity scoring, and compliance reporting.',
'Services',
'Agentic Ag',
'https://agenticag.co/carbon-biodiversity.html',
'Carbon Farming,Biodiversity,ERF,Restoration',
'{"standards": ["ERF-aligned", "Biodiversity Scoring", "Compliance Reporting"]}');

-- Insert agent information as knowledge articles
INSERT INTO reddog.KnowledgeArticles (title, content, category, source, sourceUrl, tags, metadata) VALUES
('Red Dog - AI Farm Data Assistant',
'Red Dog is an AI-powered farm data assistant that provides intelligent access to farm databases, integrates with external data providers through Trevor Tractor, manages data approval workflows, and can control farm systems. Connected databases include zerosumag, Grassgum Farm, and Pairtree. Features natural language to SQL query conversion, smart schema caching, safety checks, and credit-based billing.',
'Agents',
'Agentic Ag',
'https://github.com/sustainablehorticulture/BackendRedDogAADX',
'Red Dog,AI,Farm Data,Database Query',
'{"capabilities": ["Database Query", "External Data Integration", "Approval Workflows", "Control System"], "databases": ["zerosumag", "Grassgum Farm", "Pairtree"]}'),

('Trevor Tractor - Data Provider',
'Trevor Tractor handles data provider authentication and retrieval. Communicates with Red Dog via Service Bus. Supported providers include AADX (Australian Agriculture Data Exchange), Axistech (IoT sensors), and Pairtree (agricultural data). Provides key-brokered access for consumers.',
'Agents',
'Agentic Ag',
'https://github.com/sustainablehorticulture/bot-trevor-tractor',
'Trevor Tractor,Data Provider,AADX,Axistech,Pairtree',
'{"providers": ["AADX", "Axistech", "Pairtree"], "communication": "Service Bus"}'),

('Daisy Bell - Notification Agent',
'Daisy Bell is the third agent in the ecosystem. Potential capabilities include notification management, alert distribution, and user communication. Integration with Red Dog and Trevor Tractor for coordinated farm operations.',
'Agents',
'Agentic Ag',
'https://github.com/sustainablehorticulture/backenddaisybell',
'Daisy Bell,Notifications,Alerts,Communication',
'{"status": "In Development", "capabilities": ["Notification Management", "Alert Distribution", "User Communication"]}');

-- Insert general company information
INSERT INTO reddog.KnowledgeArticles (title, content, category, source, sourceUrl, tags, metadata) VALUES
('Agentic Ag Overview',
'Agentic Ag provides agricultural energy and IoT integrated systems for Australian farms. Based in Clarence Valley, NSW, serving North Coast region from Tweed Heads to Coffs Harbour. Services include IoT installation, drone services, soil testing, land management, consultancy, bioenergy co-op, and carbon/biodiversity services. Platform includes The Farmyard dashboard, The Toolshed, and AI agents (Red Dog, Trevor Tractor, Daisy Bell).',
'News',
'Agentic Ag',
'https://agenticag.co',
'Agentic Ag,Agricultural Technology,IoT,Australian Farms',
'{"location": "Clarence Valley, NSW", "serviceRegion": "Tweed Heads to Coffs Harbour", "platform": ["The Farmyard", "The Toolshed", "AI Agents"]}'),

('FarmG8 Marketplace',
'The FarmG8 Marketplace connects producers directly with buyers, CoOps, and processors. Features integrated logistics, carbon credit trading, transparent pricing, and live stock availability synced from Farmyard dashboard. No middlemen approach for direct farm-to-market transactions.',
'Marketplace',
'Agentic Ag',
'https://agenticag.co',
'FarmG8,Marketplace,Direct Trading,Carbon Credits',
'{"features": ["Integrated Logistics", "Carbon Credit Trading", "Transparent Pricing", "Live Stock Availability"]}');
